INSERT INTO CARDAPIO_ENTITY VALUES(1,'Massas');
INSERT INTO RECEITA_ENTITY VALUES(1,'SpamLetto',1);
INSERT INTO GRUPO_ENTITY VALUES(1,'Carboidratos',1);
INSERT INTO INGREDIENTE_ENTITY VALUES(1,'Arroz',10.00,15.00,1);